- name: Log into DockerHub
  community.docker.docker_login:
    username: "{{ docker.id }}"
    password: "{{ docker.password }}"

- name: Build and push image to Docker Hub
  community.docker.docker_image:
  repository: "{{ docker.id }}/{{ docker.repository }}:{{ docker.tag  }}"
    force_tag: yes
    push: yes
    source: build
    build:
      path: ../../../../../Dockerfile